name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: make pc_x86_64_efi_defconfig

    - name: Install dependencies
      run: make -j8
